### ISSUE TITLE
allow using custom fork for valhalla

### ISSUE THREAD

**Issue by farfromrefug** [nilsnolde/docker-valhalla#171]
Could be useful to use custom branches /repo of valhalla while PRs are being reviewed or before release
Not sure if possible.

BTW: how do we know which version of valhalla is actually used? latest, master?

THanks

**Comment by chrstnbwnkl** [comment]
Not sure GitHub Actions supports event triggers that would be necessary. Also, PR branches in the upstream repo don't build the docker image either. I simply do this in my custom forks (a Valhalla fork where pushes to PR branches trigger a docker build, and a fork of this repo that in turn builds based off my fork :smile:). I wouldn't cram all this into the upstream repo. 

We rebuild latest once every week from master, and have tagged releases for every Valhalla release. Last release was before this repo was moved away from GIS-OPS, so this one still has none.

**Comment by farfromrefug** [comment]
@chrstnbwnkl i do now maintain a fork of this repo and publish my own docker through github package as you do here.
So i guess that could be the way to go
