### ISSUE TITLE
Error while running the container on centos 8 system

### ISSUE THREAD

**Issue by Rishikeshsynosys** [nilsnolde/docker-valhalla#176]
When I tried to start the container on my server which has a centOs operating system of version 8, I got the below error, can anyone help me to fix this issue please 

ERROR :: 2024/11/26 09:22:05.674866 [WARN] Traffic tile extract could not be loaded
Too many open files (src/epoll.cpp:38)

**Comment by chrstnbwnkl** [comment]
It's possible you are using loads of threads (valhalla will try using all by default), and each thread gets a graph reader that reads parts of the graph. Usually this should be only one file if you use the tile extract (i.e. tar mode), but might be more likely to happen if you use the `tile_dir` instead. So try 1) building the tile extract, 2) using fewer threads for the service, or 3) setting  `ulimit` in your OS.

**Comment by Rishikeshsynosys** [comment]
ulimit -n
104096

The ulimit is already set to a high number and I am using the same image without any modifications but still I can see the container exiting with the error : "Too many open files"

Is there any other cause for this issue, I am running with the tar mode.

**Comment by chrstnbwnkl** [comment]
Does it also happen if you only use a single thread?

**Comment by Rishikeshsynosys** [comment]
ENV VALHALLA_NUM_THREADS=1 , I have included this in the Dockerfile but still no hope, the same issue is there, the container is searching for some files that are not found 

2024/11/26 16:44:20.653663 [WARN] (stat): /custom_files/traffic.tar No such file or directory
2024/11/26 16:44:20.653669 [WARN] Traffic tile extract could not be loaded
2024/11/26 16:44:20.654368 [INFO] Tile extract successfully loaded with tile count: 3441
2024/11/26 16:44:20.654410 [WARN] (stat): /custom_files/traffic.tar No such file or directory
2024/11/26 16:44:20.654417 [WARN] Traffic tile extract could not be loaded
Too many open files (src/ipc_listener.cpp:297)

could you please check it ?

**Comment by Rishikeshsynosys** [comment]
Just FYI : I downloaded the custom_files from this url using the wget command : 
`wget -O custom_files/gcc-states-latest.osm.pbf https://download.geofabrik.de/asia/gcc-states-latest.osm.pbf`

**Comment by Rishikeshsynosys** [comment]
![image](https://github.com/user-attachments/assets/7bae77cc-b97b-4f11-829f-c5f231f8a2e4)
